---
title: "GAM_clean"
output: html_document
date: "2024-09-10"
---

Load necessary packages and read in dataframes
```{r}
library(mgcv)
library(gamclass)
library(ggplot2)
library(randomForest)
library(car)
library(mice)
library(ggcorrplot)
library(visreg)

df_all <- read.csv("model data_V3_engsoil_removed.csv")
#df_pred_removed <- read.csv("linear model data_V2_predictors_removed_pca.csv")
df_res_removed <- read.csv("linear model data_V3_res_removed.csv")
df_subset <- read.csv("model data_V3_inf_subset.csv")
#df_binomial <- read.csv("linear model data_V2_res_removed_pca_rf_binom.csv")

#df_underdrain <- read.csv("underdrain_res_removed.csv")
#df_no_underdrain <- read.csv("no_underdrain_res_removed.csv")
```

PCA of underlying soil vars
```{r}
pca_soil_all <- prcomp(df_subset[21:26], scale=TRUE, center=TRUE)
summary(pca_soil_all)
first_pc_soil_all <- pca_soil_all$x[, 1]
second_pc_soil_all <- pca_soil_all$x[, 2]

pca_soil_all_df <- data.frame(Soil_PC_1 = first_pc_soil_all, Soil_PC_2 = second_pc_soil_all)

#df_all <- cbind(df_all, pca_soil_all_df)

write.csv(pca_soil_all_df, file = "model data_V3_subset_engvars_pca.csv")
```

Remove random sample (row) from data frame
```{r}
# Set a seed for reproducibility 
set.seed(123)

# Number of rows to remove 
n_remove <- 1

# Randomly select rows to remove 
# Change df to data frame of interest
rows_to_remove <- sample(1:nrow(df_70), n_remove)

# Remove the selected rows
# Change df to data frame of interest
df_69 <- df_70[-rows_to_remove, ]

```

Correlation Matrix
```{r}
corr_all <- cor(df_res_removed[3:43,])

# Visualize the correlation matrix using ggcorrplot
corr_matrix_all <- ggcorrplot(corr_all, 
           method = "square", 
           type = "lower", 
           lab = FALSE,
           tl.cex = 20           # Adjust text label size on axes
        +  theme(panel.background = element_rect(fill = "white", color = NA),
           plot.background = element_rect(fill = "white", color = NA)))

# Customize the axis text size using theme()
corr_matrix_all <- corr_matrix_all + theme(
  axis.text.x = element_text(size = 14), # Adjust size for x-axis labels
  axis.text.y = element_text(size = 14)  # Adjust size for y-axis labels
)

ggsave("correlation_plot_all.png", width = 15, height = 15)

```

Impute missing data using MICE:
```{r}
imputed_data <- mice(df_subset, m = 5, method = "pmm", seed = 123)

#summary(imputed_data)

imputed_df <- complete(imputed_data, 1)
```

Run random forest model for further variable selection
```{r}
#make this example reproducible
set.seed(1)

response <- df_69$Average.infiltration.rate

# With underlying soil vars: [, c("Drainage.Area.Ratio", "Age", "Ponding.Depth", "Underdrain", "Percent.Vegetation.Shrub", "Percent.Vegetation.Grass", "Percent.Vegetation.Tree", "Percent.Vegetation.Prairie", "Percent.Vegetation.Other", "Percent.of.Surface.with.Poor.Infiltration", "Vegetation.Condition", "Engineered.Soil.Depth", "Engineered.Soil.Percent.Sand", "Engineered.Soil.Percent.Compost", "Underlying.Soil.Percent.Sand", "Underlying.Soil.Percent.Silt", "Underlying.Soil.Percent.Clay", "Underlying.Soil.Percent.Urban.Disturbed", "Underlying.Soil.Percent.Other.Undefined", "Underlying.Soil.Percent.Organic.Matter", "Percent.Nonresidential")]

predictors <- df_69[, c("Drainage.Area.Ratio", "Age", "Ponding.Depth", "Underdrain", "Percent.Vegetation.Shrub", "Percent.Vegetation.Grass", "Percent.Vegetation.Tree", "Percent.Vegetation.Prairie", "Percent.Vegetation.Other", "Percent.of.Surface.with.Poor.Infiltration", "Vegetation.Condition", "Engineered.Soil.Depth", "Engineered.Soil.Percent.Sand", "Engineered.Soil.Percent.Compost", "Soil_PC_1", "Soil_PC_2", "Percent.Nonresidential")]

rf_df <- data.frame(response, predictors)

#fit the random forest model
model <- randomForest(
  formula = response ~ .,
  data = rf_df
)

#display fitted model
model

#find number of trees that produce lowest test MSE
which.min(model$mse)

#find RMSE of best model
#sqrt(model$mse[which.min(model$mse)])

# Predict the response on the training data
predictions <- predict(model, newdata = df_res_removed)

# Calculate R-squared
actual_values <- df_res_removed$Average.infiltration.rate
rss <- sum((actual_values - predictions)^2)  # Residual sum of squares (SSR)
tss <- sum((actual_values - mean(actual_values))^2)  # Total sum of squares (TSS)

r_squared <- 1 - (rss / tss)

# Print the R-squared value
print(r_squared)

# plot the test MSE by number of trees
plot(model)

# produce variable importance plot
varImpPlot(model, main = "")

```

Check for collinearity using VIF
```{r}
#Area+Contributing.Area+Drainage.Area.Ratio+Age+Ponding.Depth+Inlet.Condition+Outlet.Condition+Underdrain+Percent.Residential+Percent.Commercial+Percent.Industrial+ Percent.Institutional+Percent.Vegetation.Shrub+Percent.Vegetation.Tree+Percent.Vegetation.Grass+Percent.Vegetation.Prairie+Percent.Vegetation.Bare+Percent.Vegetation.Other+Underlying.Soil.Percent.Sand+Underlying.Soil.Percent.Silt+Underlying.Soil.Percent.Clay+Underlying.Soil.Percent.Urban.Disturbed+Underlying.Soil.Percent.Other.Undefined+Underlying.Soil.Percent.Organic.Matter+Evidence.of.Poor.Infiltration+Percent.of.Surface.with.Poor.Infiltration+Vegetation.Condition+Inlet.Feature.Curb.Cut+Inlet.Feature.Other+Inlet.Feature.Overland.Flow+Inlet.Feature.Pipe+Outlet.Feature.Other+Outlet.Feature.Overland.Flow+Outlet.Feature.Pipe+Outlet.Feature.Riser.Pipe+Engineered.Soil.Depth+Engineered.Soil.Percent.Sand+Engineered.Soil.Percent.Silt+Engineered.Soil.Percent.Clay+Engineered.Soil.Percent.Compost+Engineered.Soil.Percent.Other

# Drainage.Area.Ratio+Age+Ponding.Depth+Percent.Residential+Percent.Commercial+ Percent.Institutional+Percent.Vegetation.Shrub+Percent.Vegetation.Tree+Percent.Vegetation.Grass+Percent.Vegetation.Prairie+Percent.Vegetation.Other+Underlying.Soil.Percent.Sand+Underlying.Soil.Percent.Silt+Underlying.Soil.Percent.Clay+Underlying.Soil.Percent.Urban.Disturbed+Underlying.Soil.Percent.Organic.Matter+Percent.of.Surface.with.Poor.Infiltration+Vegetation.Condition+Engineered.Soil.Depth+Engineered.Soil.Percent.Sand+Engineered.Soil.Percent.Compost

#run lm on dataframe
vif_model <- lm(Average.infiltration.rate ~ Drainage.Area.Ratio + Age + Percent.Vegetation.Shrub + Percent.Vegetation.Other + Soil_PC_1 + Soil_PC_2 + Engineered.Soil.Percent.Sand + Engineered.Soil.Percent.Compost

, data = df_80)

#create vector of VIF values
vif_values <- vif(vif_model)

#png("VIF.all.png", width = 800, height = 600)

par(mar=c(4,20,4,4))

#create horizontal bar chart to display each VIF value
barplot(vif_values, horiz = TRUE, cex.names = 1.5, cex.axis = 1.5, las=1, col = "steelblue", main="")

#add vertical lines at 5 and 10
abline(v = 5, lwd = 2, lty = 2)
abline(v = 10, lwd = 2, lty = 2)

#dev.off()
```

Run GAM
```{r}

# s(Drainage.Area.Ratio) + s(Age) + s(Ponding.Depth) + Underdrain + s(Percent.Nonresidential) + s(Percent.Vegetation.Shrub) + s(Percent.Vegetation.Tree) + s(Percent.Vegetation.Grass) + s(Percent.Vegetation.Prairie) + s(Percent.Vegetation.Other) + s(Underlying.Soil.Percent.Sand) + s(Underlying.Soil.Percent.Silt) + s(Underlying.Soil.Percent.Clay) + s(Underlying.Soil.Percent.Urban.Disturbed) + s(Underlying.Soil.Percent.Organic.Matter) + Percent.of.Surface.with.Poor.Infiltration + Vegetation.Condition + s(Engineered.Soil.Depth) + s(Engineered.Soil.Percent.Sand) + s(Engineered.Soil.Percent.Compost)

#df_res_removed$Inf.High.Medium.Low <- factor(df_res_removed$Inf.High.Medium.Low, levels = c("Low", "Medium", "High"), ordered = TRUE)

#df_res_removed$Inf.High.Medium.Low <- as.integer(df_res_removed$Inf.High.Medium.Low)

df_res_removed$Inf.High.Low.6 <- as.factor(df_res_removed$Inf.High.Low.6)

# deleted: Age + s(Underlying.Soil.Percent.Organic.Matter) + Underlying.Soil.Percent.Clay + Underlying.Soil.Percent.Sand +  s(Engineered.Soil.Depth) 

# RF Top 12 Vars: s(Drainage.Area.Ratio) + s(Age) + s(Percent.Nonresidential) + s(Ponding.Depth) + s(Percent.Vegetation.Shrub) + s(Percent.Vegetation.Prairie) + s(Percent.Vegetation.Other) + s(Soil_PC_1) + s(Soil_PC_2) + s(Engineered.Soil.Depth) + s(Engineered.Soil.Percent.Sand) + s(Engineered.Soil.Percent.Compost) 


#run GAM
gam_model <- gam(Average.infiltration.rate ~  s(Drainage.Area.Ratio) + s(Age) + s(Ponding.Depth) + Percent.Nonresidential + s(Percent.Vegetation.Shrub) +
                 s(Percent.Vegetation.Tree) + Percent.Vegetation.Grass + s(Percent.Vegetation.Prairie) + Percent.Vegetation.Other +
                 s(Engineered.Soil.Depth) + s(Engineered.Soil.Percent.Sand) + Engineered.Soil.Percent.Compost + s(Soil_PC_1) + s(Soil_PC_2) + Underdrain  + Percent.of.Surface.with.Poor.Infiltration
, select = TRUE, data = df_res_removed)

#Determine if the k values are sufficiently high for the smoothed variables
#If p-values are significant, k is too low
gam.check(gam_model)

#Output of model performance (R2, p-values)
gam_summary <- summary(gam_model)
gam_summary

plot(gam_model, all.terms = TRUE, residuals=TRUE, pch=1, cex=1, shade=TRUE, shade.col="lightblue")

# Visualize the model, both smooth and parametric effects
visreg(gam_model, scale = "response", gg = TRUE)

# Get list of variables and associated p-values
# Extract p-values from the smooth terms and parametric terms
smooth_pvalues <- gam_summary$s.pv   # p-values for smoothed terms
param_pvalues <- gam_summary$p.pv    # p-values for parametric terms

# Combine smooth and parametric terms
pvalues <- c(smooth_pvalues, param_pvalues)

# Extract the names of the predictor variables in the same order
predictors <- c(rownames(gam_summary$s.table), rownames(gam_summary$p.table))

# Order the predictors by p-value
ordered_indices <- order(pvalues)
ordered_predictors <- predictors[ordered_indices]
ordered_pvalues <- pvalues[ordered_indices]

# Save the results in a list
results_list <- list(
  predictors = ordered_predictors,
  p_values = ordered_pvalues
)

# Assume ordered_predictors is the vector of ordered predictor names
# Remove 's()' from smooth terms using gsub()
cleaned_predictors <- gsub("s\\((.*)\\)", "\\1", ordered_predictors)

# Convert the cleaned predictor names into a single comma-separated string
predictors_string <- paste(cleaned_predictors, collapse = ", ")

# Print the result
cat(predictors_string)

# Round the p-values to 6 decimal places
rounded_pvalues <- round(ordered_pvalues, 6)

# Convert the rounded p-values into a single comma-separated string
pvalues_string <- paste(rounded_pvalues, collapse = ", ")

# Print the rounded p-values
cat(pvalues_string)
```

Check concurvity
```{r}
concurvity(gam_model, full=TRUE)
#plot(gam_model, pages = 1, trans = plogis)
```

Better plot of predicted vs measured
```{r}
predictions <- predict(gam_model)

# Make plots square (better to visualize predictions when x and y axes are the same)
par(pty="s")
# Plot measured vs predicted
plot(df_pred_removed$Average.infiltration.rate, predictions, main="",  xlab="Measured Infiltration Rate", ylab="Predicted Infiltration Rate", pch = 16, col = "palegreen2", bg="transparent", cex.axis=1)
abline(a = 0, b = 1, col = "black")
grid()
```



```{r}
source("get_gam.R")

# x <- c("Drainage.Area.Ratio", "Age", "Ponding.Depth", "Percent.Nonresidential", "Percent.Vegetation.Shrub",
#                 "Percent.Vegetation.Tree", "Percent.Vegetation.Grass", "Percent.Vegetation.Prairie", "Percent.Vegetation.Other",
#                 "Engineered.Soil.Depth", "Engineered.Soil.Percent.Sand", "Engineered.Soil.Percent.Compost", "Soil_PC_1", "Soil_PC_2")

x <- c("Drainage.Area.Ratio", "Age", "Ponding.Depth", "Percent.Nonresidential", "Percent.Vegetation.Shrub",
                     "Percent.Vegetation.Tree", "Percent.Vegetation.Grass", "Percent.Vegetation.Prairie", "Percent.Vegetation.Other",
                     "Soil_PC_1", "Soil_PC_2")

# x <- c("Drainage.Area.Ratio", "Age", "Ponding.Depth", "Percent.Nonresidential", "Percent.Vegetation.Shrub",
#                      "Percent.Vegetation.Tree", "Percent.Vegetation.Grass", "Percent.Vegetation.Prairie", "Percent.Vegetation.Other",
#                      "Underlying.Soil.Percent.Sand", "Underlying.Soil.Percent.Silt", "Underlying.Soil.Percent.Clay", 
#                      "Underlying.Soil.Percent.Urban.Disturbed", "Underlying.Soil.Percent.Other.Undefined",
#                      "Underlying.Soil.Percent.Organic.Matter", "Engineered.Soil.Depth", "Engineered.Soil.Percent.Sand",
#                      "Engineered.Soil.Percent.Compost")

x_lin <- c("Underdrain", "Vegetation.Condition", "Percent.of.Surface.with.Poor.Infiltration")

y <- df_all$Average.infiltration.rate

columns <- df_all[22:27]

get_gam(df_all, x, x_lin, y, columns, 12, 0.2)
```
```{r}
# Load the final model from the RDS file
final_model <- readRDS("final_model.rds")

visreg(final_model, scale = "response", gg = TRUE, data = df_all)
```

